
security:

    role_hierarchy:
        ROLE_ADMIN: [ROLE_CLIENT]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        app_user_provider:
            entity:
                class: App\Entity\LogInUsers
                property: email

    password_hashers:
        App\Entity\LogInUsers:
            algorithm: auto

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt))
            security: false

        admin:
            pattern: ^/admin
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_admin_login
                check_path: app_admin_login
                default_target_path: app_admin_home
                csrf_token_id: admin_authenticate
            logout:
                path: app_admin_logout
                target: app_admin_login 

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: app_home
                csrf_token_id: authenticate
            logout:
                path: app_logout
                target: app_landing  

    access_control:
        - { path: ^/admin/login, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/(login|logout|about|contact)/, roles: PUBLIC_ACCESS }
        - { path: ^/$, roles: PUBLIC_ACCESS }
        - { path: ^/client, roles: ROLE_CLIENT }
