security:

    providers:
        app_user_provider:
            entity:
                class: App\Entity\LogInUsers
                property: email
    
    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt)
            security: false
        main:
            lazy: true
            provider: app_user_provider
            
            form_login:
                login_path: app_login
                default_target_path: app_client_home 
                csrf_token_id: authenticate
                
            logout:
                path: app_logout
                target: app_landing 

    access_control:
        - { path: ^/client, roles: ROLE_CLIENT }
        - { path: ^/(login|logout|explore|about|contact)/, roles: PUBLIC_ACCESS }
        - { path: ^/$, roles: PUBLIC_ACCESS } 

