
services:

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - staygrid_mysql_network 

networks:
  staygrid_mysql_network:
    driver: bridge

    # Inside the nginx service definition in docker-compose.yaml
volumes:
  - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf