<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGMZRXpc\App_KernelLocalDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGMZRXpc/App_KernelLocalDebugContainer.php') {
    touch(__DIR__.'/ContainerGMZRXpc.legacy');

    return;
}

if (!\class_exists(App_KernelLocalDebugContainer::class, false)) {
    \class_alias(\ContainerGMZRXpc\App_KernelLocalDebugContainer::class, App_KernelLocalDebugContainer::class, false);
}

return new \ContainerGMZRXpc\App_KernelLocalDebugContainer([
    'container.build_hash' => 'GMZRXpc',
    'container.build_id' => 'b7613e00',
    'container.build_time' => 1759572282,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGMZRXpc');
