<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_homepage' => [[], ['_controller' => 'App\\Controller\\Controller::index'], [], [['text', '/']], [], [], []],
    'App\Controller\Controller::index' => [[], ['_controller' => 'App\\Controller\\Controller::index'], [], [['text', '/']], [], [], []],
];
