<?php

namespace ContainerVNmahcE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PGTzR4dService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PGTzR4d' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PGTzR4d'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'room' => ['privates', '.errored..service_locator.PGTzR4d.App\\Entity\\Room', NULL, 'Cannot autowire service ".service_locator.PGTzR4d": it needs an instance of "App\\Entity\\Room" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'room' => 'App\\Entity\\Room',
            'entityManager' => '?',
        ]);
    }
}
