<?php

namespace ContainerVNmahcE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UWYRUSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.u_wYRUS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.u_wYRUS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\RoomController::index' => ['privates', '.service_locator.XJAN2mv.App\\Controller\\RoomController::index()', 'getRoomControllerindexService', true],
            'App\\Controller\\RoomController::new' => ['privates', '.service_locator.egipcEH.App\\Controller\\RoomController::new()', 'getRoomControllernewService', true],
            'App\\Controller\\RoomController::show' => ['privates', '.service_locator.XKbFx5Y.App\\Controller\\RoomController::show()', 'getRoomControllershowService', true],
            'App\\Controller\\RoomController::edit' => ['privates', '.service_locator.PGTzR4d.App\\Controller\\RoomController::edit()', 'getRoomControllereditService', true],
            'App\\Controller\\RoomController::delete' => ['privates', '.service_locator.PGTzR4d.App\\Controller\\RoomController::delete()', 'getRoomControllerdeleteService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\RoomController:index' => ['privates', '.service_locator.XJAN2mv.App\\Controller\\RoomController::index()', 'getRoomControllerindexService', true],
            'App\\Controller\\RoomController:new' => ['privates', '.service_locator.egipcEH.App\\Controller\\RoomController::new()', 'getRoomControllernewService', true],
            'App\\Controller\\RoomController:show' => ['privates', '.service_locator.XKbFx5Y.App\\Controller\\RoomController::show()', 'getRoomControllershowService', true],
            'App\\Controller\\RoomController:edit' => ['privates', '.service_locator.PGTzR4d.App\\Controller\\RoomController::edit()', 'getRoomControllereditService', true],
            'App\\Controller\\RoomController:delete' => ['privates', '.service_locator.PGTzR4d.App\\Controller\\RoomController::delete()', 'getRoomControllerdeleteService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\RoomController::index' => '?',
            'App\\Controller\\RoomController::new' => '?',
            'App\\Controller\\RoomController::show' => '?',
            'App\\Controller\\RoomController::edit' => '?',
            'App\\Controller\\RoomController::delete' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\RoomController:index' => '?',
            'App\\Controller\\RoomController:new' => '?',
            'App\\Controller\\RoomController:show' => '?',
            'App\\Controller\\RoomController:edit' => '?',
            'App\\Controller\\RoomController:delete' => '?',
        ]);
    }
}
