<?php

namespace ContainerVNmahcE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRoomControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PGTzR4d.App\Controller\RoomController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.PGTzR4d'] ?? $container->load('get_ServiceLocator_PGTzR4dService'));

        if (isset($container->privates['.service_locator.PGTzR4d.App\\Controller\\RoomController::edit()'])) {
            return $container->privates['.service_locator.PGTzR4d.App\\Controller\\RoomController::edit()'];
        }

        return $container->privates['.service_locator.PGTzR4d.App\\Controller\\RoomController::edit()'] = $a->withContext('App\\Controller\\RoomController::edit()', $container);
    }
}
