<?php

namespace ContainerVNmahcE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRoomControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XKbFx5Y.App\Controller\RoomController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XKbFx5Y.App\\Controller\\RoomController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'room' => ['privates', '.errored..service_locator.XKbFx5Y.App\\Entity\\Room', NULL, 'Cannot autowire service ".service_locator.XKbFx5Y": it needs an instance of "App\\Entity\\Room" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'room' => 'App\\Entity\\Room',
        ]))->withContext('App\\Controller\\RoomController::show()', $container);
    }
}
