<?php

namespace ContainerVNmahcE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRoomControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PGTzR4d.App\Controller\RoomController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PGTzR4d.App\\Controller\\RoomController::delete()'] = ($container->privates['.service_locator.PGTzR4d'] ?? $container->load('get_ServiceLocator_PGTzR4dService'))->withContext('App\\Controller\\RoomController::delete()', $container);
    }
}
