<?php

namespace ContainerHYdPyLq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MRSWrGYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mRSWrGY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mRSWrGY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\Admin\\AdminHomeController::home' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\Admin\\AdminHomeController::home()', 'getAdminHomeControllerhomeService', true],
            'App\\Controller\\Admin\\AdminProfileController::edit' => ['privates', '.service_locator.A84gqGd.App\\Controller\\Admin\\AdminProfileController::edit()', 'getAdminProfileControllereditService', true],
            'App\\Controller\\Admin\\AdminSecurityController::login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\Admin\\AdminSecurityController::login()', 'getAdminSecurityControllerloginService', true],
            'App\\Controller\\Admin\\RoomListingController::index' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\Admin\\RoomListingController::index()', 'getRoomListingControllerindexService', true],
            'App\\Controller\\Admin\\RoomListingController::new' => ['privates', '.service_locator.egipcEH.App\\Controller\\Admin\\RoomListingController::new()', 'getRoomListingControllernewService', true],
            'App\\Controller\\Admin\\RoomListingController::edit' => ['privates', '.service_locator.2YmAlWk.App\\Controller\\Admin\\RoomListingController::edit()', 'getRoomListingControllereditService', true],
            'App\\Controller\\Admin\\RoomListingController::delete' => ['privates', '.service_locator.2YmAlWk.App\\Controller\\Admin\\RoomListingController::delete()', 'getRoomListingControllerdeleteService', true],
            'App\\Controller\\Admin\\SecurityAdminController::login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\Admin\\SecurityAdminController::login()', 'getSecurityAdminControllerloginService', true],
            'App\\Controller\\Admin\\UserController::index' => ['privates', '.service_locator.H_jJJSp.App\\Controller\\Admin\\UserController::index()', 'getUserControllerindexService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.tEL1pRK.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\RegistrationController::verifyUserEmail' => ['privates', '.service_locator.KHhLDTq.App\\Controller\\RegistrationController::verifyUserEmail()', 'getRegistrationControllerverifyUserEmailService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\Admin\\AdminHomeController:home' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\Admin\\AdminHomeController::home()', 'getAdminHomeControllerhomeService', true],
            'App\\Controller\\Admin\\AdminProfileController:edit' => ['privates', '.service_locator.A84gqGd.App\\Controller\\Admin\\AdminProfileController::edit()', 'getAdminProfileControllereditService', true],
            'App\\Controller\\Admin\\AdminSecurityController:login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\Admin\\AdminSecurityController::login()', 'getAdminSecurityControllerloginService', true],
            'App\\Controller\\Admin\\RoomListingController:index' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\Admin\\RoomListingController::index()', 'getRoomListingControllerindexService', true],
            'App\\Controller\\Admin\\RoomListingController:new' => ['privates', '.service_locator.egipcEH.App\\Controller\\Admin\\RoomListingController::new()', 'getRoomListingControllernewService', true],
            'App\\Controller\\Admin\\RoomListingController:edit' => ['privates', '.service_locator.2YmAlWk.App\\Controller\\Admin\\RoomListingController::edit()', 'getRoomListingControllereditService', true],
            'App\\Controller\\Admin\\RoomListingController:delete' => ['privates', '.service_locator.2YmAlWk.App\\Controller\\Admin\\RoomListingController::delete()', 'getRoomListingControllerdeleteService', true],
            'App\\Controller\\Admin\\SecurityAdminController:login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\Admin\\SecurityAdminController::login()', 'getSecurityAdminControllerloginService', true],
            'App\\Controller\\Admin\\UserController:index' => ['privates', '.service_locator.H_jJJSp.App\\Controller\\Admin\\UserController::index()', 'getUserControllerindexService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.tEL1pRK.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\RegistrationController:verifyUserEmail' => ['privates', '.service_locator.KHhLDTq.App\\Controller\\RegistrationController::verifyUserEmail()', 'getRegistrationControllerverifyUserEmailService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\Admin\\AdminHomeController::home' => '?',
            'App\\Controller\\Admin\\AdminProfileController::edit' => '?',
            'App\\Controller\\Admin\\AdminSecurityController::login' => '?',
            'App\\Controller\\Admin\\RoomListingController::index' => '?',
            'App\\Controller\\Admin\\RoomListingController::new' => '?',
            'App\\Controller\\Admin\\RoomListingController::edit' => '?',
            'App\\Controller\\Admin\\RoomListingController::delete' => '?',
            'App\\Controller\\Admin\\SecurityAdminController::login' => '?',
            'App\\Controller\\Admin\\UserController::index' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\RegistrationController::verifyUserEmail' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\Admin\\AdminHomeController:home' => '?',
            'App\\Controller\\Admin\\AdminProfileController:edit' => '?',
            'App\\Controller\\Admin\\AdminSecurityController:login' => '?',
            'App\\Controller\\Admin\\RoomListingController:index' => '?',
            'App\\Controller\\Admin\\RoomListingController:new' => '?',
            'App\\Controller\\Admin\\RoomListingController:edit' => '?',
            'App\\Controller\\Admin\\RoomListingController:delete' => '?',
            'App\\Controller\\Admin\\SecurityAdminController:login' => '?',
            'App\\Controller\\Admin\\UserController:index' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\RegistrationController:verifyUserEmail' => '?',
            'App\\Controller\\SecurityController:login' => '?',
        ]);
    }
}
