<?php

namespace ContainerHYdPyLq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminSecurityControllerloginService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3QECKYg.App\Controller\Admin\AdminSecurityController::login()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3QECKYg.App\\Controller\\Admin\\AdminSecurityController::login()'] = ($container->privates['.service_locator.3QECKYg'] ?? $container->load('get_ServiceLocator_3QECKYgService'))->withContext('App\\Controller\\Admin\\AdminSecurityController::login()', $container);
    }
}
