<?php

namespace Container8DdxN5R;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2YmAlWkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2YmAlWk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2YmAlWk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'roomListing' => ['privates', '.errored..service_locator.2YmAlWk.App\\Entity\\RoomListing', NULL, 'Cannot autowire service ".service_locator.2YmAlWk": it needs an instance of "App\\Entity\\RoomListing" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'roomListing' => 'App\\Entity\\RoomListing',
            'entityManager' => '?',
        ]);
    }
}
