<?php

namespace Container8DdxN5R;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRoomListingControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jMTCc26.App\Controller\RoomListingController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jMTCc26.App\\Controller\\RoomListingController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'roomListing' => ['privates', '.errored..service_locator.jMTCc26.App\\Entity\\RoomListing', NULL, 'Cannot autowire service ".service_locator.jMTCc26": it needs an instance of "App\\Entity\\RoomListing" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'roomListing' => 'App\\Entity\\RoomListing',
        ]))->withContext('App\\Controller\\RoomListingController::show()', $container);
    }
}
