<?php

namespace Container8DdxN5R;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRoomListing2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.jMTCc26.App\Entity\RoomListing' shared service.
     *
     * @return \App\Entity\RoomListing
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.jMTCc26": it needs an instance of "App\\Entity\\RoomListing" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
