<?php

namespace ContainerIrJLvxd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BCbNn46Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BCbNn46' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BCbNn46'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.tEL1pRK.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\RegistrationController::verifyUserEmail' => ['privates', '.service_locator.KHhLDTq.App\\Controller\\RegistrationController::verifyUserEmail()', 'getRegistrationControllerverifyUserEmailService', true],
            'App\\Controller\\RoomListingController::index' => ['privates', '.service_locator.9rVqUkE.App\\Controller\\RoomListingController::index()', 'getRoomListingControllerindexService', true],
            'App\\Controller\\RoomListingController::new' => ['privates', '.service_locator.egipcEH.App\\Controller\\RoomListingController::new()', 'getRoomListingControllernewService', true],
            'App\\Controller\\RoomListingController::show' => ['privates', '.service_locator.jMTCc26.App\\Controller\\RoomListingController::show()', 'getRoomListingControllershowService', true],
            'App\\Controller\\RoomListingController::edit' => ['privates', '.service_locator.2YmAlWk.App\\Controller\\RoomListingController::edit()', 'getRoomListingControllereditService', true],
            'App\\Controller\\RoomListingController::delete' => ['privates', '.service_locator.2YmAlWk.App\\Controller\\RoomListingController::delete()', 'getRoomListingControllerdeleteService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.tEL1pRK.App\\Controller\\RegistrationController::register()', 'getRegistrationControllerregisterService', true],
            'App\\Controller\\RegistrationController:verifyUserEmail' => ['privates', '.service_locator.KHhLDTq.App\\Controller\\RegistrationController::verifyUserEmail()', 'getRegistrationControllerverifyUserEmailService', true],
            'App\\Controller\\RoomListingController:index' => ['privates', '.service_locator.9rVqUkE.App\\Controller\\RoomListingController::index()', 'getRoomListingControllerindexService', true],
            'App\\Controller\\RoomListingController:new' => ['privates', '.service_locator.egipcEH.App\\Controller\\RoomListingController::new()', 'getRoomListingControllernewService', true],
            'App\\Controller\\RoomListingController:show' => ['privates', '.service_locator.jMTCc26.App\\Controller\\RoomListingController::show()', 'getRoomListingControllershowService', true],
            'App\\Controller\\RoomListingController:edit' => ['privates', '.service_locator.2YmAlWk.App\\Controller\\RoomListingController::edit()', 'getRoomListingControllereditService', true],
            'App\\Controller\\RoomListingController:delete' => ['privates', '.service_locator.2YmAlWk.App\\Controller\\RoomListingController::delete()', 'getRoomListingControllerdeleteService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\RegistrationController::verifyUserEmail' => '?',
            'App\\Controller\\RoomListingController::index' => '?',
            'App\\Controller\\RoomListingController::new' => '?',
            'App\\Controller\\RoomListingController::show' => '?',
            'App\\Controller\\RoomListingController::edit' => '?',
            'App\\Controller\\RoomListingController::delete' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\RegistrationController:verifyUserEmail' => '?',
            'App\\Controller\\RoomListingController:index' => '?',
            'App\\Controller\\RoomListingController:new' => '?',
            'App\\Controller\\RoomListingController:show' => '?',
            'App\\Controller\\RoomListingController:edit' => '?',
            'App\\Controller\\RoomListingController:delete' => '?',
            'App\\Controller\\SecurityController:login' => '?',
        ]);
    }
}
