<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHYdPyLq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHYdPyLq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHYdPyLq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHYdPyLq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHYdPyLq\App_KernelDevDebugContainer([
    'container.build_hash' => 'HYdPyLq',
    'container.build_id' => 'bd056b10',
    'container.build_time' => 1761312053,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHYdPyLq');
