<?php

namespace Container3wYiZBg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRoomListingControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2YmAlWk.App\Controller\Admin\RoomListingController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.2YmAlWk'] ?? $container->load('get_ServiceLocator_2YmAlWkService'));

        if (isset($container->privates['.service_locator.2YmAlWk.App\\Controller\\Admin\\RoomListingController::edit()'])) {
            return $container->privates['.service_locator.2YmAlWk.App\\Controller\\Admin\\RoomListingController::edit()'];
        }

        return $container->privates['.service_locator.2YmAlWk.App\\Controller\\Admin\\RoomListingController::edit()'] = $a->withContext('App\\Controller\\Admin\\RoomListingController::edit()', $container);
    }
}
