<?php

namespace Container3wYiZBg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRoomListingControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2YmAlWk.App\Controller\Admin\RoomListingController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2YmAlWk.App\\Controller\\Admin\\RoomListingController::delete()'] = ($container->privates['.service_locator.2YmAlWk'] ?? $container->load('get_ServiceLocator_2YmAlWkService'))->withContext('App\\Controller\\Admin\\RoomListingController::delete()', $container);
    }
}
